apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-turn-tcp
  annotations:
    {{- range $key, $value := $.Values.service.annotations }}
      "{{ $key }}": "{{ tpl $value $ }}"
    {{- end }}
spec:
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{.Values.service.externalTrafficPolicy}}
  {{- end }}
  {{- if .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{.Values.service.internalTrafficPolicy}}
  {{- end }}
  ports:
    - name: turn-tcp
      port: {{ .Values.coturn.ports.listening }}
      protocol: TCP
      targetPort: {{ .Values.coturn.ports.listening }}
    - name: turn-tcp-tls
      port: {{ .Values.coturn.ports.tlsListening }}
      protocol: TCP
      targetPort: {{ .Values.coturn.ports.tlsListening }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- range .Values.service.externalIPs }}
    - {{ . }}
    {{- end }}
  {{- end }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | default "" }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  sessionAffinityConfig:
    {{- if eq .Values.service.sessionAffinity "ClientIP" }}
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds | default 10800 }}
    {{- end }}